### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by Fishrock123** [indutny/derivepass#6]
- Latest `gypkg`
- npm 4.6.1
- OS X 10.12.4
- Latest XCode

```
[====================================------------------------------------] 0.0s
[========================================================================] 0.0s
/Users/Jeremiah/npm/lib/node_modules/gypkg/bin/gypkg:91
      throw err;
      ^
Error: events.js:168
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (Error: gpg failed:
gpg: keyring `/var/folders/9w/qy6qgrrj0vn8r5j8hkzjnmy40000gn/T/scoped-gpg-ah3V13/keyring' created
gpg: requesting key 6A4781FB from hkp server keyserver.linux.it
gpgkeys: HTTP fetch error 6: Couldn't resolve host 'keyserver.linux.it'
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper internal error
gpg: keyserver communications error: General error
gpg: keyserver receive failed: General error

    at async.waterfall (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/scoped-gpg/lib/scoped-gpg.js:154:18)
    at nextTask (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:5210:14)
    at /Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:5204:13
    at apply (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:21:25)
    at /Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:56:12
    at /Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:944:16
    at getTTY (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/scoped-gpg/lib/scoped-gpg.js:149:28)
    at getTTY (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/scoped-gpg/lib/scoped-gpg.js:116:12)
    at async.waterfall (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/scoped-gpg/lib/scoped-gpg.js:149:7)
    at nextTask (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:5210:14))
    at CommandSocket.emit (events.js:166:17)
    at parse (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/gypkg-cmd-socket/index.js:17:12)
    at lines.forEach.line (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/gypkg-cmd-socket/index.js:29:27)
    at Array.forEach (native)
    at Socket.CommandSocket.socket.on (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/gypkg-cmd-socket/index.js:29:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)

    at async.waterfall (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/git-secure-tag/lib/git-secure-tag/api.js:65:27)
    at nextTask (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:5210:14)
    at /Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:5204:13
    at apply (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:21:25)
    at /Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:56:12
    at /Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:944:16
    at /Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:3824:9
    at /Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:460:16
    at iterateeCallback (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:965:24)
    at /Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:944:16
/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/gyp.js/lib/gyp/input.js:2689
      throw e;
      ^

Error: Command failed: gypkg deps "git://github.com/indutny/scrypt.git@^1.0.1 [gpg] => scrypt.gyp:scrypt"

/Users/Jeremiah/npm/lib/node_modules/gypkg/bin/gypkg:91
      throw err;
      ^
Error: events.js:168
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (Error: gpg failed:
gpg: keyring `/var/folders/9w/qy6qgrrj0vn8r5j8hkzjnmy40000gn/T/scoped-gpg-ah3V13/keyring' created
gpg: requesting key 6A4781FB from hkp server keyserver.linux.it
gpgkeys: HTTP fetch error 6: Couldn't resolve host 'keyserver.linux.it'
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper internal error
gpg: keyserver communications error: General error
gpg: keyserver receive failed: General error

    at async.waterfall (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/scoped-gpg/lib/scoped-gpg.js:154:18)
    at nextTask (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:5210:14)
    at /Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:5204:13
    at apply (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:21:25)
    at /Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:56:12
    at /Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:944:16
    at getTTY (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/scoped-gpg/lib/scoped-gpg.js:149:28)
    at getTTY (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/scoped-gpg/lib/scoped-gpg.js:116:12)
    at async.waterfall (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/scoped-gpg/lib/scoped-gpg.js:149:7)
    at nextTask (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:5210:14))
    at CommandSocket.emit (events.js:166:17)
    at parse (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/gypkg-cmd-socket/index.js:17:12)
    at lines.forEach.line (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/gypkg-cmd-socket/index.js:29:27)
    at Array.forEach (native)
    at Socket.CommandSocket.socket.on (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/gypkg-cmd-socket/index.js:29:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)

    at async.waterfall (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/git-secure-tag/lib/git-secure-tag/api.js:65:27)
    at nextTask (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:5210:14)
    at /Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:5204:13
    at apply (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:21:25)
    at /Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:56:12
    at /Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:944:16
    at /Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:3824:9
    at /Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:460:16
    at iterateeCallback (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:965:24)
    at /Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/async/dist/async.js:944:16

Call to 'gypkg deps "git://github.com/indutny/scrypt.git@^1.0.1 [gpg] => scrypt.gyp:scrypt" failed while in /Users/Jeremiah/Documents/derivepass/derivepass.gyp
while trying to load /Users/Jeremiah/Documents/derivepass/derivepass.gyp
    at checkExecSyncError (child_process.js:481:13)
    at Object.execSync (child_process.js:521:13)
    at Input.execSync (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/gyp.js/lib/gyp/input.js:80:23)
    at _loop (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/gyp.js/lib/gyp/input.js:691:26)
    at Input.expandVariables (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/gyp.js/lib/gyp/input.js:781:5)
    at Input.processVariablesAndConditionsInList (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/gyp.js/lib/gyp/input.js:1119:27)
    at /Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/gyp.js/lib/gyp/input.js:1095:14
    at Array.forEach (native)
    at Input.processVariablesAndConditionsInDict (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/gyp.js/lib/gyp/input.js:1084:24)
    at Input.processVariablesAndConditionsInList (/Users/Jeremiah/npm/lib/node_modules/gypkg/node_modules/gyp.js/lib/gyp/input.js:1117:12)
/Users/Jeremiah/npm/lib/node_modules/gypkg/bin/gypkg:70
      throw err;
      ^

Error: GYP failure
    at ChildProcess.proc.on (/Users/Jeremiah/npm/lib/node_modules/gypkg/lib/gypkg/server.js:204:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! derivepass@1.0.0 install: `gypkg build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the derivepass@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Jeremiah/.npm/_logs/2017-04-23T22_02_56_289Z-debug.log
```

**Comment by Fishrock123** [comment]
`gypkg build --insecure` fixes this

**Comment by indutny** [comment]
Looking at:

```
gpg: keyring `/var/folders/9w/qy6qgrrj0vn8r5j8hkzjnmy40000gn/T/scoped-gpg-ah3V13/keyring' created
gpg: requesting key 6A4781FB from hkp server keyserver.linux.it
gpgkeys: HTTP fetch error 6: Couldn't resolve host 'keyserver.linux.it'
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper internal error
gpg: keyserver communications error: General error
gpg: keyserver receive failed: General error
```

It seems that `gpg` is not configured on the system. By default, `gypkg` will attempt to verify the signed tags of downloaded modules, this is a security feature.
